source 'https://rubygems.org'
ruby '2.2.0'
gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'omniauth-facebook'
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
gem 'bootstrap-sass'
gem 'devise'
gem 'figaro', '>= 1.0.0.rc1'
gem 'mysql2'
gem 'simple_form'
gem 'cancancan', '~> 1.10'
gem 'carrierwave'
gem 'friendly_id', '~> 5.1.0'
gem 'rails_admin'
gem "fog-aws"
gem 'fog'
group :development do
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
end
