development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shopping_cart_development
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shopping_cart_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shopping_cart_production
  pool: 5
  username: root
  password: root
  host: localhost